Config with pure python
zopefoundation/zope.globalrequest pull request #10
Opened 2021-03-26 14:27 UTC by icemac

Add support for Python 3.9.

2021-03-26 16:24 UTC, dataflake requested changes

2021-03-26 16:24 UTC, dataflake commented on MANIFEST.in
> +recursive-include src *.pt
I have merges that last PR on the meta package, please re-run to avoid warnings

2021-03-26 16:24 UTC, dataflake commented on setup.py
> +        'Programming Language :: Python :: Implementation :: CPython',
Would you mind adding `python_requires` and `project_urls`?

2021-03-27 10:17 UTC, dataflake approved these changes

2021-03-29 05:52 UTC, merged

2021-03-29 05:52 UTC, icemac commented
Thank you for reviewing and improving this PR. 😃